# Site settings
title :      code - lucatironi
tagline:     Code snippets and tutorials
description: "Ruby (on Rails), Mobile Development, Android/iOS, Rubymotion, API development tutorials"

url:               http://lucatironi.github.io
baseurl:           ''

email:             luca.tironi@gmail.com
twitter_username:  lucatironi
github_username:   lucatironi

exclude: ["README.md"]
highlighter: pygments
markdown:   kramdown
permalink:  pretty
relative_permalinks: true
